name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - run: make
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK.TOKEN }}
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: f34ceae388c1da2f1daa4bff4053e2940de18054817c0a36cddba568b4250b8a
        with:
          coverageCommand: gradlew jacocoTestReport
#  coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup JDK 17
#        uses: actions/setup-java@v2
#        with:
#          java-version: 17
#          distribution: 'temurin'
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: build
#          build-root-directory: app
#      - uses: paambaati/codeclimate-action@v2.2.4
#        env:
#          CC_TEST_REPORTER_ID: f34ceae388c1da2f1daa4bff4053e2940de18054817c0a36cddba568b4250b8a
#        with:
#          coverageCommand: ./gradlew jacocoTestReport
